services:
  # Backend Service
  - type: web
    name: live-polling-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: CLIENT_URL
        fromService:
          type: web
          name: live-polling-client
          property: host
      - key: MONGO_URI
        sync: false # User must input this manually in Dashboard
    plan: free

  # Frontend Static Site
  - type: web
    name: live-polling-client
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SOCKET_URL
        fromService:
          type: web
          name: live-polling-server
          property: host
    plan: free
